import Head from "next/head";
import Link from "next/link";
import { Button, Form, Input } from "antd";

import { api } from "~/utils/api";
import toast, { Toaster } from "react-hot-toast";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { loginLocalStorage } from "../loghelper/loghelper";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    if (localStorage.getItem("user")) {
      router.push("/");
    }
  });
  const [form] = Form.useForm();
  const { mutate, isLoading } = api.student.getStudentLogin.useMutation({
    onSuccess: (data) => {
      if (data.hasEmail && data.login) {
        toast.success("Login");
        form.resetFields();
        loginLocalStorage("student", data.login.id);
      } else if (!data.login && data.hasEmail) {
        toast.error("Incorrect password");
        form.setFields([
          {
            name: "password",
            errors: ["Incorrect Password"],
          },
        ]);
      } else {
        toast.error("Student ID not registered");
        form.setFields([
          {
            name: "password",
            errors: [""],
          },
          {
            name: "studentId",
            errors: ["Student ID not registered "],
          },
        ]);
      }
    },
  });
  const handleLogin = (e: any) => {
    mutate({
      id: e.studentId,
      password: e.password,
    });
  };

  return (
    <>
      <Head>
        <title>NWSSU Donation</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-body flex min-h-screen flex-col items-center  bg-gradient-to-b from-[#62d5b5] to-[#3ba9ac]">
        <div className=" flex min-h-screen w-11/12 flex-col items-center transition-all  duration-300 sm:w-4/12">
          <div className=" flex w-full flex-col items-center rounded  px-5 py-10 text-5xl font-semibold ">
            <img src="/nwssu.png" alt="nwssu" className=" w-1/3 " />
            <div className=" mb-5 rounded-lg text-center text-5xl font-semibold text-white ">
              NSSWU Donation
            </div>
            <div className=" flex w-full flex-col items-center justify-center gap-5 rounded-lg bg-white  p-10 text-2xl font-semibold text-slate-600 ">
              <span className=" text-lg font-medium text-[#3ba9ac]">
                Login as Student of NWSSU
              </span>
              <Form className=" w-full" form={form} onFinish={handleLogin}>
                <span className=" pl-1 text-lg text-slate-600">Student Id</span>
                <Form.Item
                  name={"studentId"}
                  rules={[{ required: true, message: "Input your Student ID" }]}
                >
                  <Input size="large" placeholder="Input your Student ID" />
                </Form.Item>
                <span className=" pl-1 text-lg text-slate-600">Password</span>
                <Form.Item
                  name={"password"}
                  rules={[{ required: true, message: "Input your password" }]}
                >
                  <Input.Password size="large" placeholder="Input Password" />
                </Form.Item>
                <Button
                  htmlType="submit"
                  className=" mt-0 h-10 w-full border-none bg-gradient-to-b from-[#62d5b5] to-[#3ba9ac] text-white hover:brightness-90"
                >
                  <span className="text-xl text-white hover:text-white">
                    {isLoading ? "Loading..." : "Login"}
                  </span>
                </Button>
                <div className=" mt-2 flex w-full flex-1 items-end justify-center text-base font-normal text-slate-700">
                  Not registered yet?{" "}
                  <span className=" mx-1">
                    <a href="/register" className=" text-[#62d5b5]">
                      Register
                    </a>
                  </span>
                </div>
              </Form>
              <span className=" mt-10 items-center text-center text-xs font-light">
                Make a meaningful impact by contributing your gently-used items
                to assist those who require help.
              </span>
              <span className=" -mt-5 items-center text-center text-base font-normal">
                <a href="/donorLogin" className=" text-[#62d5b5]">
                  Donate now!
                </a>
              </span>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
