import Head from "next/head";
import Link from "next/link";
import { Button, Form, Input } from "antd";

import { api } from "~/utils/api";
import toast, { Toaster } from "react-hot-toast";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { loginLocalStorage } from "../loghelper/loghelper";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    if (localStorage.getItem("user")) {
      router.push("/");
    }
  });
  const [form] = Form.useForm();
  const { mutate, isLoading } = api.student.getStudentLogin.useMutation({
    onSuccess: (data) => {
      if (data.hasEmail && data.login) {
        if (data.login?.activated) {
          toast.success("Login");
          form.resetFields();
          loginLocalStorage("student", data.login.id);
        } else {
          toast.error("Student Deactivated");
          form.setFields([
            {
              name: "password",
              errors: [""],
            },
            {
              name: "studentId",
              errors: [""],
            },
          ]);
        }
      } else if (!data.login && data.hasEmail) {
        toast.error("Incorrect password");
        form.setFields([
          {
            name: "password",
            errors: ["Incorrect Password"],
          },
        ]);
      } else {
        toast.error("Student ID not registered");
        form.setFields([
          {
            name: "password",
            errors: [""],
          },
          {
            name: "studentId",
            errors: ["Student ID not registered "],
          },
        ]);
      }
    },
  });
  const handleLogin = (e: any) => {
    mutate({
      id: e.studentId,
      password: e.password,
    });
  };

  return (
    <>
      <Head>
        <title>NWSSU Donation</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b  from-[#a9edda] to-[#75d7db] font-body">
        <div className=" flex min-h-screen w-11/12 flex-col items-center transition-all  duration-300 sm:w-96">
          <div className=" mt-4 flex w-full flex-col items-center  rounded px-5 text-3xl font-semibold sm:mt-0 sm:py-10 ">
            <img src="/nwssu.png" alt="nwssu" className=" w-1/3 " />
            <div className=" rounded-lg text-center font-semibold text-white sm:mb-5 sm:text-5xl ">
              NWSSU Donation
            </div>
            <div className=" flex w-full flex-col items-center justify-center gap-5 rounded-lg text-2xl  font-semibold text-slate-600 sm:bg-white sm:p-10 ">
              <span className=" text-base font-normal sm:text-2xl sm:font-semibold  sm:text-[#3ba9ac]">
                Login as Student of NWSSU
              </span>
              <Form className=" w-full" form={form} onFinish={handleLogin}>
                <span className=" pl-1 text-sm text-slate-600 sm:text-lg">
                  Student Id
                </span>
                <Form.Item
                  name={"studentId"}
                  rules={[{ required: true, message: "Input your Student ID" }]}
                >
                  <Input size="large" placeholder="Input your Student ID" />
                </Form.Item>
                <span className=" pl-1 text-sm text-slate-600 sm:text-lg">
                  Password
                </span>
                <Form.Item
                  name={"password"}
                  rules={[{ required: true, message: "Input your password" }]}
                >
                  <Input.Password size="large" placeholder="Input Password" />
                </Form.Item>
                <Button
                  htmlType="submit"
                  className=" mt-0 h-10 w-full rounded-full border-none bg-gradient-to-b from-[#62d5b5] to-[#3ba9ac] text-white shadow-lg hover:brightness-90"
                >
                  <span className="text-xl text-white hover:text-white">
                    {isLoading ? "Loading..." : "Login"}
                  </span>
                </Button>
                <div className=" mt-2 flex w-full flex-1 items-end justify-center text-base font-normal text-slate-700">
                  Not registered yet?{" "}
                  <span className=" mx-1">
                    <a
                      href="/studentRegister"
                      className=" text-[#b1ffe9] sm:text-[#62d5b5]"
                    >
                      Register
                    </a>
                  </span>
                </div>
              </Form>
              <span className=" items-center text-center text-xs font-light">
                Make a meaningful impact by contributing your gently-used items
                to assist those who require help.
              </span>
              <div className=" flex flex-row gap-6">
                <span className=" -mt-5 items-center text-center text-base font-normal">
                  <a
                    href="/"
                    className=" text-white no-underline sm:text-gray-600"
                  >
                    Back home
                  </a>
                </span>
                <span className=" -mt-5 items-center text-center text-base font-normal">
                  <a
                    href="/donorLogin"
                    className=" text-[#b1ffe9] sm:text-[#62d5b5]"
                  >
                    Donate now!
                  </a>
                </span>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
