import Head from "next/head";
import Link from "next/link";
import { Button, Form, Input, Select } from "antd";

import { api } from "~/utils/api";
import toast, { Toaster } from "react-hot-toast";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { loginLocalStorage } from "../loghelper/loghelper";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    if (localStorage.getItem("user")) {
      router.push("/");
    }
  });
  const [form] = Form.useForm();
  const { mutate } = api.donor.createDonor.useMutation({
    onSuccess: (data) => {
      toast.success("Donor Registered");
      form.resetFields();
      loginLocalStorage("donor", data.id);
    },
    onError: (error) => {
      toast.error(error.message);
      form.setFields([
        {
          name: "username",
          errors: [""],
        },
      ]);
    },
  });
  const handleRegister = (e: any) => {
    mutate({
      ...e,
    });
  };
  return (
    <>
      <Head>
        <title>NWSSU Donation</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#62d5b5] to-[#3ba9ac] font-body">
        <div className=" flex min-h-screen w-11/12 flex-col items-center transition-all duration-300  sm:w-4/12">
          <div className=" flex w-full flex-col items-center rounded  px-5 py-10 text-5xl font-semibold ">
            <div className=" mb-2 flex flex-row items-center justify-center">
              <img src="/nwssu.png" alt="nwssu" className=" w-20 " />
              <div className=" mx-auto rounded-lg text-center text-4xl font-semibold text-white ">
                NWSSU Donation
              </div>
            </div>
            <div className=" flex w-full flex-col items-center justify-center gap-0 rounded-lg bg-white  p-10 text-2xl font-semibold text-slate-600 ">
              <span className="mb-2 text-xl font-medium text-[#3ba9ac]">
                Register as Donor
              </span>
              <span className=" rounded bg-[#e4feff] p-2 text-center text-sm font-light text-[#3ba9ac]">
                Your gently-used items can make a significant difference for
                those in need.
              </span>
              <Form
                className=" mt-5 w-full"
                form={form}
                onFinish={handleRegister}
              >
                <span className=" pl-1 text-sm text-slate-600">Username</span>
                <Form.Item
                  name={"username"}
                  rules={[{ required: true, message: "" }]}
                >
                  <Input size="large" placeholder="Input your username" />
                </Form.Item>
                <div className=" flex flex-row gap-1">
                  <div className=" flex flex-1 flex-col">
                    <span className=" pl-1 text-sm text-slate-600">
                      First Name
                    </span>
                    <Form.Item
                      name={"firstName"}
                      rules={[{ required: true, message: "" }]}
                    >
                      <Input size="large" placeholder="First name" />
                    </Form.Item>
                  </div>
                  <div className=" flex flex-1 flex-col">
                    <span className=" pl-1 text-sm text-slate-600">
                      Last Name
                    </span>
                    <Form.Item
                      name={"lastName"}
                      rules={[{ required: true, message: "" }]}
                    >
                      <Input size="large" placeholder="Last name" />
                    </Form.Item>
                  </div>
                </div>
                <div className=" flex flex-row gap-1">
                  <div className=" flex flex-1 flex-col">
                    <span className=" pl-1 text-sm text-slate-600">
                      Alumni of NWSSU ?
                    </span>
                    <Form.Item
                      name="alumni"
                      rules={[{ required: true, message: "" }]}
                    >
                      <Select
                        placeholder={"Are you an alumni of NWSSU?"}
                        size="large"
                      >
                        {[
                          { id: true, name: "Yes" },
                          { id: false, name: "No" },
                        ]?.map((b: any) => (
                          <Select.Option key={b.id} value={b.id}>
                            {b.name}
                          </Select.Option>
                        ))}
                      </Select>
                    </Form.Item>
                  </div>
                </div>
                <div className=" flex flex-row gap-1">
                  <div className=" flex flex-1 flex-col">
                    <span className=" pl-1 text-sm text-slate-600">
                      Password
                    </span>
                    <Form.Item
                      name="password"
                      rules={[{ required: true, message: "" }]}
                    >
                      <Input.Password size="large" placeholder="Password" />
                    </Form.Item>
                  </div>
                </div>
                <div className=" flex flex-row gap-1">
                  <div className=" flex flex-1 flex-col">
                    <span className=" pl-1 text-sm text-slate-600">
                      Confirm Password
                    </span>
                    <Form.Item
                      name="confirmPass"
                      rules={[
                        {
                          validator: async (_: any, value: any) => {
                            if (value !== form.getFieldValue("password")) {
                              return Promise.reject(
                                new Error("Password does not match."),
                              );
                            }
                          },
                        },
                      ]}
                    >
                      <Input.Password
                        size="large"
                        placeholder="Confirm Password"
                      />
                    </Form.Item>
                  </div>
                </div>
                <Button
                  htmlType="submit"
                  className=" mt-0 h-10 w-full border-none bg-gradient-to-b from-[#62d5b5] to-[#3ba9ac] text-white hover:brightness-90"
                >
                  <span className="text-xl text-white hover:text-white">
                    Register
                  </span>
                </Button>
                <div className=" mt-2 flex w-full flex-1 items-end justify-center text-base font-normal text-slate-700">
                  Already registered?{" "}
                  <span className=" mx-1">
                    <a href="/donorLogin" className=" text-[#62d5b5]">
                      Login
                    </a>
                  </span>
                </div>
              </Form>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
