import Head from "next/head";
import Link from "next/link";
import { Button, Form, Input, Select } from "antd";

import { api } from "~/utils/api";
import toast, { Toaster } from "react-hot-toast";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { loginLocalStorage } from "../loghelper/loghelper";

export default function Home() {
  const router = useRouter();
  const [donorType, setDonorType] = useState("Donor");
  useEffect(() => {
    if (localStorage.getItem("user")) {
      router.push("/");
    }
  });
  const [form] = Form.useForm();
  const { mutate } = api.donor.createDonor.useMutation({
    onSuccess: (data) => {
      toast.success("Donor Registered");
      form.resetFields();
      loginLocalStorage("donor", data.id);
    },
    onError: (error) => {
      toast.error(error.message);
      form.setFields([
        {
          name: "username",
          errors: [""],
        },
      ]);
    },
  });
  const handleRegister = (e: any) => {
    mutate({
      username: e.username,
      name: e.name,
      address: e.address,
      password: e.password,
      alumni: e.alumni,
      contact: e.contact,
      type: e.type,
    });
  };
  useEffect(() => {
    form.setFieldValue("type", donorType);
  }, [donorType]);
  return (
    <>
      <Head>
        <title>NWSSU Donation</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b  from-[#a9edda] to-[#75d7db] font-body">
        <div className=" flex min-h-screen w-11/12 flex-col items-center transition-all duration-300  sm:w-4/12">
          <div className=" flex w-full flex-col items-center rounded  px-5 py-2 text-5xl font-semibold sm:py-10 ">
            <div className=" flex flex-col items-center justify-center sm:mb-2 sm:flex-row">
              <img src="/nwssu.png" alt="nwssu" className=" w-20 " />
              <div className=" mx-auto rounded-lg text-center text-xl font-semibold text-white sm:text-4xl ">
                NWSSU Donation
              </div>
            </div>
            <div className=" flex w-full flex-col items-center justify-center gap-0 rounded-lg text-2xl  font-semibold text-slate-600 sm:bg-white sm:p-10 ">
              <span className="mb-2 text-base font-medium text-[#3ba9ac] sm:text-xl">
                Register as Donor
              </span>
              <Form
                className=" w-full sm:mt-5"
                form={form}
                onFinish={handleRegister}
              >
                <span className=" pl-1 text-sm text-slate-600">
                  Register as :
                </span>
                <Form.Item
                  name="type"
                  rules={[{ required: true, message: "" }]}
                >
                  <Select
                    placeholder={"Select Registration Type"}
                    size="large"
                    onChange={(e) => setDonorType(e)}
                    defaultValue={donorType}
                  >
                    {[
                      { id: "Donor", name: "Individual" },
                      { id: "Organization", name: "Organization" },
                    ]?.map((b: any) => (
                      <Select.Option key={b.id} value={b.id}>
                        {b.name}
                      </Select.Option>
                    ))}
                  </Select>
                </Form.Item>
                <span className=" pl-1 text-sm text-slate-600">Username</span>
                <Form.Item
                  name={"username"}
                  rules={[{ required: true, message: "" }]}
                >
                  <Input size="large" placeholder="Input your username" />
                </Form.Item>
                <div className=" flex flex-row gap-1">
                  <div className=" flex flex-1 flex-col">
                    <span className=" pl-1 text-sm text-slate-600">
                      {`${donorType}` + " Name"}
                    </span>
                    <Form.Item
                      name={"name"}
                      rules={[{ required: true, message: "" }]}
                    >
                      <Input size="large" placeholder="Input name" />
                    </Form.Item>
                  </div>
                </div>
                <div className=" flex flex-row gap-1">
                  <div className=" flex flex-1 flex-col">
                    <span className=" pl-1 text-sm text-slate-600">
                      Mobile Number
                    </span>
                    <Form.Item
                      name="contact"
                      rules={[{ required: true, message: "" }]}
                    >
                      <Input size="large" placeholder="09*********" />
                    </Form.Item>
                  </div>
                  {donorType === "Donor" && (
                    <div className=" flex flex-1 flex-col">
                      <span className=" pl-1 text-sm text-slate-600">
                        Alumni of NWSSU ?
                      </span>
                      <Form.Item
                        name="alumni"
                        rules={[{ required: true, message: "" }]}
                      >
                        <Select placeholder={"Alumni of NWSSU?"} size="large">
                          {[
                            { id: true, name: "Yes" },
                            { id: false, name: "No" },
                          ]?.map((b: any) => (
                            <Select.Option key={b.id} value={b.id}>
                              {b.name}
                            </Select.Option>
                          ))}
                        </Select>
                      </Form.Item>
                    </div>
                  )}
                </div>
                <div className=" flex flex-1 flex-col">
                  <span className=" pl-1 text-sm text-slate-600">
                    {donorType + " address"}
                  </span>
                  <Form.Item
                    name="address"
                    rules={[{ required: true, message: "" }]}
                  >
                    <Input size="large" placeholder="Input address" />
                  </Form.Item>
                </div>
                <div className=" flex flex-row gap-1">
                  <div className=" flex flex-1 flex-col">
                    <span className=" pl-1 text-sm text-slate-600">
                      Password
                    </span>
                    <Form.Item
                      name="password"
                      rules={[{ required: true, message: "" }]}
                    >
                      <Input.Password size="large" placeholder="Password" />
                    </Form.Item>
                  </div>
                </div>
                <div className=" flex flex-row gap-1">
                  <div className=" flex flex-1 flex-col">
                    <span className=" pl-1 text-sm text-slate-600">
                      Confirm Password
                    </span>
                    <Form.Item
                      name="confirmPass"
                      rules={[
                        {
                          validator: async (_: any, value: any) => {
                            if (value !== form.getFieldValue("password")) {
                              return Promise.reject(
                                new Error("Password does not match."),
                              );
                            }
                          },
                        },
                      ]}
                    >
                      <Input.Password
                        size="large"
                        placeholder="Confirm Password"
                      />
                    </Form.Item>
                  </div>
                </div>
                <Button
                  htmlType="submit"
                  className=" mt-0 h-10 w-full border-none bg-gradient-to-b from-[#62d5b5] to-[#3ba9ac] text-white hover:brightness-90"
                >
                  <span className="text-xl text-white hover:text-white">
                    Register
                  </span>
                </Button>
                <div className=" mt-2 flex w-full flex-1 items-end justify-center text-base font-normal text-slate-700">
                  Already registered?{" "}
                  <span className=" mx-1">
                    <a
                      href="/donorLogin"
                      className=" text-white sm:text-[#62d5b5]"
                    >
                      Login
                    </a>
                  </span>
                </div>
                <span className="flex w-full items-center justify-center text-base font-normal">
                  <a
                    href="/"
                    className=" text-center text-white no-underline sm:text-gray-600"
                  >
                    Back home
                  </a>
                </span>
              </Form>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
