import Head from "next/head";
import Link from "next/link";
import { Button, Form, Input } from "antd";

import { api } from "~/utils/api";
import toast, { Toaster } from "react-hot-toast";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { loginLocalStorage } from "../loghelper/loghelper";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    if (localStorage.getItem("user") === "student") {
      router.push("/student");
    } else if (localStorage.getItem("user") === "admin") {
      router.push("/admin");
    } else if (localStorage.getItem("user") === "donor") {
      router.push("/donor");
    }
  });
  const [form] = Form.useForm();
  const { mutate, isLoading } = api.donor.getDonorLogin.useMutation({
    onSuccess: (data) => {
      if (data.hasEmail && data.login) {
        toast.success(`Login as ${data.type}`);
        form.resetFields();
        loginLocalStorage(data.type, data.login.id);
      } else if (!data.login && data.hasEmail) {
        toast.error("Incorrect password");
        form.setFields([
          {
            name: "password",
            errors: ["Incorrect Password"],
          },
        ]);
      } else {
        toast.error("Username not found");
        form.setFields([
          {
            name: "password",
            errors: [""],
          },
          {
            name: "username",
            errors: ["Username not found"],
          },
        ]);
      }
    },
  });
  const handleLogin = (e: any) => {
    mutate({
      username: e.username,
      password: e.password,
    });
  };

  return (
    <>
      <Head>
        <title>NWSSU Donation</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b  from-[#a9edda] to-[#75d7db] font-body">
        <div className=" flex min-h-screen w-11/12 flex-col items-center transition-all  duration-300 sm:w-96">
          <div className=" mt-4 flex w-full flex-col items-center  rounded px-5 text-5xl font-semibold sm:mt-0 sm:py-10 ">
            <img src="/nwssu.png" alt="nwssu" className=" w-1/3 " />
            <div className=" rounded-lg text-center text-3xl font-semibold text-white sm:mb-5 ">
              NWSSU Donation
            </div>
            <div className=" flex w-full flex-col items-center rounded-lg text-2xl font-semibold  text-slate-600 sm:justify-center sm:bg-white sm:p-10 ">
              <span className=" text-sm font-medium text-[#3ba9ac] sm:text-2xl">
                Login as Donor / Admin
              </span>
              <span className=" mt-1 rounded bg-[#e4feff] text-center text-xs font-light text-[#3ba9ac] sm:mt-0 sm:p-2 sm:text-sm">
                Your gently-used items can make a significant difference for
                those in need.
              </span>
              <Form className=" mt-5 w-full" form={form} onFinish={handleLogin}>
                <span className=" pl-1 text-slate-600 sm:text-lg">
                  Username
                </span>
                <Form.Item
                  name={"username"}
                  rules={[{ required: true, message: "Input your username" }]}
                >
                  <Input size="large" placeholder="Input your username" />
                </Form.Item>
                <span className=" pl-1 text-slate-600 sm:text-lg">
                  Password
                </span>
                <Form.Item
                  name={"password"}
                  rules={[{ required: true, message: "Input your password" }]}
                >
                  <Input.Password size="large" placeholder="Input Password" />
                </Form.Item>
                <Button
                  htmlType="submit"
                  className=" mt-0 h-10 w-full rounded-full border-none bg-gradient-to-b from-[#62d5b5] to-[#3ba9ac] text-white shadow-lg hover:brightness-90"
                >
                  <span className="text-xl text-white hover:text-white">
                    {isLoading ? "Loading..." : "Login"}
                  </span>
                </Button>
                <div className=" mt-2 flex w-full flex-1 items-end justify-center text-sm font-normal text-slate-700 sm:text-base">
                  Not registered yet?{" "}
                  <span className=" mx-1">
                    <a
                      href="/donorRegister"
                      className=" text-[#dbfff5] sm:text-[#62d5b5] "
                    >
                      Register
                    </a>
                  </span>
                </div>
                <span className="flex w-full items-center justify-center gap-2 text-base font-normal">
                  <a
                    href="/"
                    className=" text-center text-white no-underline sm:text-gray-600"
                  >
                    Back home
                  </a>
                  <a
                    href="/login"
                    className=" items-center p-2 text-center font-normal text-[#ffffff] sm:text-sm sm:text-[#62d5b5]"
                  >
                    Login as Student
                  </a>
                </span>
              </Form>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
